### ISSUE TITLE
invalid reference format

### ISSUE THREAD

**Issue by Lerentis** [pauvos/ansible#1]
Hello There,

just saw your repo on the docker hub and wanted to test it with drone:0.8, but i always get the error `Error response from daemon: invalid reference format` Did I miss something?

My .drone.yml:

```yml
pipeline:
  build:
    image: chmuul/ansible:$$OS
    commands:
      - ansible-playbook -i tests/inventory update-debian.yml --syntax-check
      - ansible-playbook -i tests/inventory update-debian.yml
      
matrix:
   OS:
     - debian-8
     - ubuntu-16.04
```

* Docker version 18.01.0-ce, build 03596f51b1
